### ISSUE TITLE
No module named 'ldap.filter'

### ISSUE THREAD

**Issue by elitzer2** [django-auth-ldap/django-auth-ldap#118]
I recently upgraded from django-auth-ldap version 1.3.0 to the latest 1.7.0 and when importing  django_auth_ldap.config I am getting the following error:
`>>> import django_auth_ldap.config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/venv/lib/python3.6/site-packages/django_auth_ldap/config.py", line 38, in <module>
    import ldap.filter
ModuleNotFoundError: No module named 'ldap.filter'
`

If I do a pip list I see the python-ldap module installed and I also have the openldap-devel yum package installed. I am on CentOS 7.6 using Python 3.6.8. Any ideas?

**Comment by elitzer2** [comment]
I built a clean CentOS and re-installed the pip package and now it works. Must've been an uninstall/install issue with pip and it didn't clean up properly.
