### ISSUE TITLE
The logging documentation snippet isn't complete

### ISSUE THREAD

**Issue by aaronlelevier** [django-auth-ldap/django-auth-ldap#120]
I was trying the [logging documentation](https://django-auth-ldap.readthedocs.io/en/latest/logging.html), but the snippet isn't complete, and I got the error:

```
(venv) alelevier@ ~/Documents/drifter/drift_backend (ldap) $ ./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10f8858c8>
Traceback (most recent call last):
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/alelevier/Documents/drifter/venv/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 495, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
```

I changed the logging to this boilerplate config and it worked:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django_auth_ldap': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    }
}
```

Maybe the [logging documentation](https://django-auth-ldap.readthedocs.io/en/latest/logging.html) could be updated to the above snippet?

**Comment by jdufresne** [comment]
Thanks for catching that. Would you like to submit a fix as a PR?

**Comment by aaronlelevier** [comment]
Sure, I will submit PR. Thanks
