### ISSUE TITLE
Null ID insertion issues 

### ISSUE THREAD

**Issue by Rubyj** [django-auth-ldap/django-auth-ldap#132]
@jdufresne 

I have changed my DN slightly (users moved to a new location in Active Directory). I have verified I have the correct DN and it works to login. However, as soon as the handshake is performed, django_auth_ldap errors out because it is not able to insert a new row into the `auth_user_groups` table.

`django_auth_ldap WARNING null value in column "id" violates not-null constraint`
`DETAIL: Failing row contains (null, 1, 8)`
`WARNING [django_auth_ldap] [backend.py:395] - null value in column "id" violates not-null constraint`

The user authenticates correctly but then django_auth_ldap is causing an error because it can not insert a new user_group into the database.

If I set `AUTH_LDAP_ALWAYS_UPDATE_USER` to false then I can login successfully and the error goes away.

Why is this happening? Why is this plugin not able to update my users and groups in django successfully and trying to insert null ids? Does this have to do with the fact that my users changes DN(s) in Active directory? Someone please help!

**Comment by Rubyj** [comment]
@jdufresne Here is an example stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 196, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 150, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 210, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
    self._get_or_create_user()
django.db.utils.IntegrityError: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, !ENCRYPTEDPASSWORDEHERE, null, t, rjacobs, , , , t, t, 2019-06-05 19:05:12.956966+00).
```
