### ISSUE TITLE
Tests fail with Python 3.10

### ISSUE THREAD

**Issue by ignatenkobrain** [django-auth-ldap/django-auth-ldap#257]
Hello,

We've been trying to run django-auth-ldap tests on Fedora with Python 3.10 but 2 tests started to fail (3.9 is fine).

```
======================================================================
FAIL: test_deprecated_cache_groups (tests.tests.LDAPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/django-auth-ldap-2.4.0/tests/tests.py", line 1578, in test_deprecated_cache_groups
    self.assertEqual(len(w), 1)
AssertionError: 5 != 1
======================================================================
FAIL: test_deprecated_callable_server_uri (tests.tests.LDAPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/django-auth-ldap-2.4.0/tests/tests.py", line 195, in test_deprecated_callable_server_uri
    self.assertEqual(len(w), 1)
AssertionError: 5 != 1
----------------------------------------------------------------------
```

Can you take a look, please?

**Comment by francoisfreitag** [comment]
Thanks for reporting. The tests are failing because Python 3.10 raises:

```
django/utils/asyncio.py:19: DeprecationWarning: There is no current event loop
  event_loop = asyncio.get_event_loop()
```

The tests are capturing 3 years-old deprecation warnings, and expect only one warning. With Django warnings, a total of 5 warnings are captured.

I’ll make a 3.0.0 version sometimes next week that drops the deprecated settings, solving the issue.
