### ISSUE TITLE
ModuleNotFoundError: No module named 'ldap.filter'

### ISSUE THREAD

**Issue by danielar79** [django-auth-ldap/django-auth-ldap#293]
Hi! 
I'm using the latest versions of this package and python-ldap. I have everything updated and the docker packages too but there is no way that the docker will not stop if active for example:"from django_auth_ldap.config import LDAPSearch", it makes me exited(1). 
Can you help me?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/app/manage.py", line 22, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 343, in run_from_argv

    connections.close_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 232, in close_all

    for alias in self:

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 226, in __iter__

    return iter(self.databases)

  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__

    res = instance.__dict__[self.name] = self.func(instance)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 153, in databases

    self._databases = settings.DATABASES

  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__

    self._setup(name)

  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup

    self._wrapped = Settings(settings_module)

  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 790, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/usr/src/app/api_config/settings.py", line 15, in <module>

    from django_auth_ldap.config import LDAPSearch

  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/config.py", line 36, in <module>

    import ldap.filter

ModuleNotFoundError: No module named 'ldap.filter'

**Comment by danielar79** [comment]
django-auth-ldap==4.0.0
  - Django [required: >=2.2, installed: 3.1.14]
    - asgiref [required: >=3.2.10,<4, installed: 3.3.1]
    - pytz [required: Any, installed: 2021.1]
    - sqlparse [required: >=0.2.2, installed: 0.4.2]
  - **python-ldap [required: >=3.1, installed: 3.1.0]**
    - pyasn1 [required: >=0.3.7, installed: 0.4.8]
    - pyasn1-modules [required: >=0.1.5, installed: 0.2.8]
      - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]

Yes it's installed but it's like it can't find ldap.filter in config.py
