### ISSUE TITLE
unsupported format character '(' (0x28) at index 8

### ISSUE THREAD

**Issue by michelbf** [django-auth-ldap/django-auth-ldap#324]
Wondering if anyone came across this issue. I have just configured settings.py with the configuration instructions but when I try to login to the admin URL, I'm getting this error. Would greatly appreaciate any help:

```
Environment:


Request Method: POST
Request URL: http://myserver.xyz/admin/login/?next=/admin/

Django Version: 4.1.5
Python Version: 3.9.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'prereqs']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 438, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 459, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 217, in clean
    self.user_cache = authenticate(
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 142, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 200, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 342, in authenticate
    self._authenticate_user_dn(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 472, in _authenticate_user_dn
    if self.dn is None:
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 437, in dn
    self._load_user_dn()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 508, in _load_user_dn
    self._user_dn = cache.get_or_set(
  File "/usr/local/lib/python3.9/site-packages/django/core/cache/backends/base.py", line 228, in get_or_set
    default = default()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 533, in _search_for_user_dn
    results = search.execute(self.connection, {"user": self._username})
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/config.py", line 146, in execute
    filterstr = self.filterstr % filterargs

Exception Type: ValueError at /admin/login/
Exception Value: unsupported format character '(' (0x28) at index 8
```

**Comment by francoisfreitag** [comment]
Unsure what version of django-auth-ldap you are using?
On `master`: https://github.com/django-auth-ldap/django-auth-ldap/blob/a6e03c6e4f793edbace8371ea4d42e56c5e833bf/django_auth_ldap/config.py#L200

The `filterargs` should have been escaped through `self._escape_filterargs(filterargs)`, delegating to `ldap.filter.escape_filter_chars()`, which should escape the `(` to `\28`.

Anyway, in order to get more help, please provide:
- the version of the library you are using,
- the settings you’ve defined,
- exerpt of your code that are relevant,
- a minimal project to reproduce the issue would be very helpful,
- ideally, a failing test case.

**Comment by michelbf** [comment]
Hi @francoisfreitag 
I just found the issue this morning. It seems when I copied some code from the manual, I accidentally badly formatted it.

So I had:
```
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=users,dc=vorcan,dc=xyz", ldap.SCOPE_SUBTREE, "(uid= % (user)s)"
)
```
And as soon as I removed the spaces in `(uid= % (user)s)`, it worked fine!
