### ISSUE TITLE
AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.

### ISSUE THREAD

**Issue by snburkitt** [django-auth-ldap/django-auth-ldap#353]
Having a small issue with logins. (Code and logs provided have been redacted)

When a user logins in successfully, everything works as expected. When a user login fails, I would like Django to return a 401 error. However, the login is failing with error code 500.

When I check the server logs, I see the following trace:

```
Binding as CN=******,OU=******,OU=Users,OU=******,DC=******,DC=******,DC=com
Invoking search_s('DC=****,DC=****,DC=com', 2, '(sAMAccountName=****)')
search_s('DC=****,DC=****,DC=com', 2, '(sAMAccountName=%(user)s)') returned 1 objects: cn=simon ****,ou=production,ou=users,ou=****,DC=****,DC=****,DC=com
Binding as cn=simon ****,ou=production,ou=users,ou=****,DC=****,DC=****,DC=com
Authentication failed for ****: user DN/password rejected by LDAP server.
AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance. while authenticating ****
Internal Server Error: /django/api-auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 242, in clean
    self.user_cache = authenticate(
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 148, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/django/proof_ldap/backends.py", line 13, in authenticate_ldap_user
    user = ldap_user.authenticate(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 348, in authenticate
    self._authenticate_user_dn(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 478, in _authenticate_user_dn
    if self.dn is None:
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 443, in dn
    self._load_user_dn()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 516, in _load_user_dn
    self._user_dn = self._search_for_user_dn()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 554, in _search_for_user_dn
    return _search_for_user()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 535, in _search_for_user
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.
```

My Django settings file is configured as below:
```
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "DC=****,DC=****,DC=com",
    ldap.SCOPE_SUBTREE,
    "(sAMAccountName=%(user)s)",
)

AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 1,
    ldap.OPT_REFERRALS: 0,
}

AUTH_LDAP_SERVER_URI = os.environ["AUTH_LDAP_SERVER_URI"]

AUTH_LDAP_BIND_DN = os.environ["AUTH_LDAP_BIND_DN"]
AUTH_LDAP_BIND_PASSWORD = os.environ["AUTH_LDAP_BIND_PASSWORD"]


AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
    "dn": "distinguishedName",
}

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "DC=******,DC=******,DC=com",
    ldap.SCOPE_SUBTREE,
    "(sAMAccountName=%(user)s)",
)

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "DC=******,DC=******,DC=com", ldap.SCOPE_SUBTREE, "(objectClass=group)"
)


AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType()

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_staff": os.environ["AUTH_LDAP_SUPERUSER"],
    "is_superuser": os.environ["AUTH_LDAP_SUPERUSER"],
}

AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300


AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_MIRROR_GROUPS = True
```

Again, successful login works. Only failed logins produce this error.

**Comment by francoisfreitag** [comment]
It is surprising. It means the `settings.USER_SEARCH is None` based on https://github.com/django-auth-ldap/django-auth-ldap/blob/e94c7b21a73c1fcb5191e13f1c1ffff554dce324/django_auth_ldap/backend.py#L533-L537

However, your user search settings do not seem to be `None`. Could you try to replicate the failure in a development environment?

The library has a test that should represent your use case, so you should be getting `None` for the user. https://github.com/django-auth-ldap/django-auth-ldap/blob/e94c7b21a73c1fcb5191e13f1c1ffff554dce324/tests/tests.py#L231-L244

**Comment by snburkitt** [comment]
Thanks for the info, but I found the issue. Was my fault. I originally wrote this code over a year ago for another project, and just copied the settings over. I forgot that I had extended the LDAPBackend class to prevent login if the LDAP account didn't have an email address.

```
class LDAP_PIBackend(LDAPBackend):
    def authenticate_ldap_user(self, ldap_user, password):
        user = ldap_user.authenticate(password)

        if not user:
            return None

        if not user.email:
            logger.warning(f"User {user} has no email address. Unable to login.")
            return None

        logger.info(f"{user} login successful!")
        return user
```

As soon as I went back to the default backend, I no longer get the error on a failed login. I assume that the issue was that I was returning None if the authenticate method failed?

**Comment by francoisfreitag** [comment]
Returning `None` for failed authentication should be supported. Django iterates over authentication backends until one of them returns a `User` (or authentication fails when all backends returned `None`).
The `LDAPBackend` returns `None` for empty passwords, empty usernames or invalid passwords. The issue is probably deeper in the code.
