### ISSUE TITLE
'tuple' object has no attribute 'search_with_additional_term_string'

### ISSUE THREAD

**Issue by krowix** [django-auth-ldap/django-auth-ldap#54]
Hi,

After  successfull login on Active Directory i have this error

```
[Tue Jun 05 15:35:08 2018] [error] Traceback (most recent call last):
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\core\\handlers\\base.py", line 149, in get_response
[Tue Jun 05 15:35:08 2018] [error]     response = self.process_exception_by_middleware(e, request)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\core\\handlers\\base.py", line 147, in get_response
[Tue Jun 05 15:35:08 2018] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\views\\decorators\\cache.py", line 57, in _wrapped_view_func
[Tue Jun 05 15:35:08 2018] [error]     response = view_func(request, *args, **kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\contrib\\admin\\sites.py", line 413, in login
[Tue Jun 05 15:35:08 2018] [error]     return login(request, **defaults)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\contrib\\auth\\views.py", line 49, in inner
[Tue Jun 05 15:35:08 2018] [error]     return func(*args, **kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\views\\decorators\\debug.py", line 76, in sensitive_post_parameters_wrapper
[Tue Jun 05 15:35:08 2018] [error]     return view(request, *args, **kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\utils\\decorators.py", line 149, in _wrapped_view
[Tue Jun 05 15:35:08 2018] [error]     response = view_func(request, *args, **kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\views\\decorators\\cache.py", line 57, in _wrapped_view_func
[Tue Jun 05 15:35:08 2018] [error]     response = view_func(request, *args, **kwargs)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\contrib\\auth\\views.py", line 69, in login
[Tue Jun 05 15:35:08 2018] [error]     if form.is_valid():
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\forms\\forms.py", line 161, in is_valid
[Tue Jun 05 15:35:08 2018] [error]     return self.is_bound and not self.errors
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\forms\\forms.py", line 153, in errors
[Tue Jun 05 15:35:08 2018] [error]     self.full_clean()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\forms\\forms.py", line 363, in full_clean
[Tue Jun 05 15:35:08 2018] [error]     self._clean_form()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\forms\\forms.py", line 390, in _clean_form
[Tue Jun 05 15:35:08 2018] [error]     cleaned_data = self.clean()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\contrib\\auth\\forms.py", line 159, in clean
[Tue Jun 05 15:35:08 2018] [error]     password=password)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django\\contrib\\auth\\__init__.py", line 74, in authenticate
[Tue Jun 05 15:35:08 2018] [error]     user = backend.authenticate(**credentials)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 167, in authenticate
[Tue Jun 05 15:35:08 2018] [error]     user = ldap_user.authenticate(password)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 339, in authenticate
[Tue Jun 05 15:35:08 2018] [error]     self._get_or_create_user()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 561, in _get_or_create_user
[Tue Jun 05 15:35:08 2018] [error]     self._populate_user()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 588, in _populate_user
[Tue Jun 05 15:35:08 2018] [error]     self._populate_user_from_group_memberships()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 601, in _populate_user_from_group_memberships
[Tue Jun 05 15:35:08 2018] [error]     value = any(self._get_groups().is_member_of(dn) for dn in group_dns)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 601, in <genexpr>
[Tue Jun 05 15:35:08 2018] [error]     value = any(self._get_groups().is_member_of(dn) for dn in group_dns)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 816, in is_member_of
[Tue Jun 05 15:35:08 2018] [error]     is_member = (group_dn in self.get_group_dns())
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 828, in get_group_dns
[Tue Jun 05 15:35:08 2018] [error]     group_infos = self._get_group_infos()
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\backend.py", line 840, in _get_group_infos
[Tue Jun 05 15:35:08 2018] [error]     self._group_search)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\config.py", line 543, in user_groups
[Tue Jun 05 15:35:08 2018] [error]     ldap_user.connection)
[Tue Jun 05 15:35:08 2018] [error]   File "E:\\Python27\\lib\\site-packages\\django_auth_ldap\\config.py", line 561, in find_groups_with_any_member
[Tue Jun 05 15:35:08 2018] [error]     search = group_search.search_with_additional_term_string(filterstr)
[Tue Jun 05 15:35:08 2018] [error] AttributeError: 'tuple' object has no attribute 'search_with_additional_term_string'
```

Could you help me ?

**Comment by jdufresne** [comment]
Can you paste the contents of your `settings.py`, most importantly `AUTH_LDAP_GROUP_SEARCH`? It looks like something is incorrectly defined as a tuple.

**Comment by jdufresne** [comment]
If you're able to answer the question above and demonstrate that this is a bug in django-auth-ldap (and not simply a configuration issue) please leave a comment so I can reopen and investigate a deeper fix. Until then, I believe I have answered the original questions. Thanks!
